all:
	@echo "NOTE: The following six 'illegal[1-6]' tests are expected to all fail!"
	-../../enchex illegal1.hex | ../../emreti
	-../../enchex illegal2.hex | ../../emreti
	-../../enchex illegal3.hex | ../../emreti
	-../../enchex illegal4.hex | ../../emreti
	-../../enchex illegal5.hex | ../../emreti
	-../../enchex illegal6.hex | ../../emreti
clean:
